# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        '/:title'

# Setup
title:            'OpenWRT x86_64'
tagline:          '14.07 (Barrier Breaker)'
description:      '14.07 (Barrier Breaker)'
url:              http://pdf.github.io
baseurl:          /openwrt-14.07-x86_64

author:
  name:           'Peter Fern'
  url:            https://github.com/pdf

paginate:         5

# Custom vars
version:          r43693-001

github:
  repo:           https://github.com/pdf/openwrt-14.07-x86_64
